### ISSUE TITLE
[0.791] AvD, Assault and CP capping problems

### ISSUE THREAD

**Issue by APGRoboCop** [APGRoboCop/foxbot#1]
> then we gotta focus on 0.791
> and i might have found something interesting regarding that
> Syntax error, unrecognised command
> 
> on_start
>  {
>   blue_attack 
>   red_attack 
>   blue_available_only_point3
>   red_available_only_point1
>  }
> on_msg(RED SECURITY IS DOWN
> 
>  ACCESS TO RED FLAG IS AVAILABLE!)
>  {
>   blue_available_only_point4
>  }
> on_msg(BLUE SECURITY IS DOWN
> 
>  ACCESS TO BLUE FLAG IS AVAILABLE!)
>  {
>   red_available_only_point2
>  }
> on_msg(RED FLAG ACCESS:
> 
>  DENIED!)
>  {
>   blue_available_only_point3
>  }
> 
> on_msg(BLUE FLAG ACCESS:
> 
>  DENIED!)
>  {
>   red_available_only_point1
>  }
> 
> on_msg(RED FLAG ACCESS:
> 
>  10 SECONDS REMAINING...)
>  {
>   blue_available_point3
>  }
> 
> on_msg(BLUE FLAG ACCESS:
> 
>  10 SECONDS REMAINING...)
>  {
>   red_available_point1
>  }
> something here went wrong on 0.791 beta 2
> it might be our hint to figuring out what's wrong with A/D and other maps that stopped working properly on 0.79

Reported by [APG]BLACKiE

**Comment by ghost** [comment]
Wait, wasn't this fixed on 0.791? can't you close this issue?

**Comment by APGRoboCop** [comment]
It is fixed now.
